# Generated by Django 4.1.1 on 2022-10-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('idVoo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('companhiaAerea', models.CharField(max_length=20)),
                ('origem', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=20)),
                ('partidaPrevista', models.DateTimeField()),
                ('partidaReal', models.DateTimeField(null=True)),
                ('chegadaPrevista', models.DateTimeField()),
                ('chegadaReal', models.DateTimeField(null=True)),
                ('statusVoo', models.CharField(max_length=100)),
                ('conexoes', models.CharField(max_length=100)),
                ('ultimaAtualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voos',
            },
        ),
    ]
